### ISSUE TITLE
bad/slow grid feed in control

### ISSUE THREAD

**Issue by transistorgit** [Dr-Gigavolt/dbus-aggregate-batteries#16]
This is more like a question or maybe an improvement suggestion

My ESS tries to regulate the grid injection to zero (grid feed in setpoint 50W) what is working quite nice. As soon I switched over to Aggregate batteries, the feed in regulation is much worse.

What can be the cause? DC values from the battery shoudn't be used for grid regulation, but maybe the system gets slower with AggregateBatteries, 2*Daly Serial Battery and Smartshunt running in parallel, compared to just only having smarshunt alone before?

Graph: without Aggregate Batteries until 06:30, and with AB afterwards
![image](https://user-images.githubusercontent.com/6627385/224355084-29112337-a029-433c-978f-8ca9e40e1fd0.png)

![image](https://user-images.githubusercontent.com/6627385/224355568-7f1e9cd8-c518-4231-899e-76e70882d56d.png)

**Comment by Dr-Gigavolt** [comment]
Hello, since I use the DBusMonitor instead of VEdbusItemImport I haven't observe any delays. The serial-batteries send once per second, AggregateBatteries as well. My ESS set point is zero and it regulates a bit negative, apx. -20...-50W. Have you set both to AggregateBatteries? System setup -》Battery monitor and DVCC -》 Controling BMS? If everything ok, please check in device list whether AggregateBatteries updates values with the same speed as the SerialBatteries. Optionally you can add a command logging the time at the beginning of _update() and check if it writes once per second.
Best regards, 
Anton

**Comment by Dr-Gigavolt** [comment]
I've just tried to bypass my service - no difference in grid set point observed.

**Comment by transistorgit** [comment]
I found a bug in the serial port implementation of serialbattery. Will test a bit more and add it to my pull request there.
Problem was that the Dalys send broken packages quite often and then and the serial_read function waits for up to 15s for the missing bytes. I think this may be the cause for the slow update.
