### ISSUE TITLE
How is the SOC calculated?

### ISSUE THREAD

**Issue by kr0815** [Dr-Gigavolt/dbus-aggregate-batteries#18]
I finally got this tool running now - really nice
I totally prefer to use the internal shunt, dbus-seriallbattery only to observe at cell level

What i don´t unterstand: How is SOC calculated?

In the file "charge" i give an estimation of actuall SOC - i´d say thats Ah - not percent?

Is there something like a reset mechanism that sets the SOC to 100% on a certain cell voltage?

**Comment by Dr-Gigavolt** [comment]
Own SOC is a Coulomb counter. It is to replace the BMS SOC measurement if this is useless (e.g. JK BMS due to inaccurate current measurement and no reset unless the BMS protection trips).

Currents of all in the _settings.py_ registered current measurement devices (Multis, MPPTs and Smartshunts) are added together and discrete integrated with dt = 1s. The Ah (not %) are stored in the _charge_ file. 

The counter is reset to 100% if (CHARGE_VOLTAGE * number of cells) or MAX_CELL_VOLTAGE (of single cell) is reached by charging.

And it is reset to 0% if (DISCHARGE_VOLTAGE  * number of cells) or MIN_CELL_VOLTAGE (of single cell) is reached by discharge.

As this question is not an issue I close it.
