### ISSUE TITLE
Possible to integrate MQTT Battery?

### ISSUE THREAD

**Issue by Zahnpasta83** [Dr-Gigavolt/dbus-aggregate-batteries#51]
Is there a way to integrate data from a battery based on MQTT Battery together with batteries based on Serial Battery?

**Comment by Dr-Gigavolt** [comment]
Hello and excuse the late reply. I have no experience with MQTT, therefore I do not plan to integrate it. You can make a fork and modify the code as you need. But the MQTT runs over IP, doesn't it? Due to safety reason I would not do it, the communication channel should be as simple (and therefore reliable) as possible. Serial of any kind works further even if the router id down.
